rules:
    - id: domain
      enabled: false
      pattern: ""
    - id: path
      enabled: false
      pattern: ""
    - id: domain_url
      enabled: false
      pattern: ""
    - id: ip
      enabled: false
      pattern: ""
    - id: ip_url
      enabled: false
      pattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
    - id: email
      enabled: true
      pattern: \b[A-Za-z0-9._\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,61}\b
    - id: id_card
      enabled: true
      pattern: \b([1-9]\d{5}(19|20)\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx])\b
    - id: phone
      enabled: true
      pattern: \b1[3-9]\d{9}\b
    - id: jwt_token
      enabled: true
      pattern: eyJ[A-Za-z0-9_/+\-]{10,}={0,2}\.[A-Za-z0-9_/+\-\\]{15,}={0,2}\.[A-Za-z0-9_/+\-\\]{10,}={0,2}
    - id: Aliyun_AK_ID
      enabled: true
      pattern: \bLTAI[A-Za-z\d]{12,30}\b
    - id: QCloud_AK_ID
      enabled: true
      pattern: \bAKID[A-Za-z\d]{13,40}\b
    - id: JDCloud_AK_ID
      enabled: true
      pattern: \bJDC_[0-9A-Z]{25,40}\b
    - id: AWS_AK_ID
      enabled: true
      pattern: '["''''](?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}["'''']'
    - id: VolcanoEngine_AK_ID
      enabled: true
      pattern: \b(?:AKLT|AKTP)[a-zA-Z0-9]{35,50}\b
    - id: Kingsoft_AK_ID
      enabled: true
      pattern: \bAKLT[a-zA-Z0-9-_]{16,28}\b
    - id: GCP_AK_ID
      enabled: true
      pattern: \bAIza[0-9A-Za-z_\-]{35}\b
    - id: secret_key
      enabled: true
      pattern: ""
    - id: bearer_token
      enabled: true
      pattern: \b[Bb]earer\s+[a-zA-Z0-9\-=._+/\\]{20,500}\b
    - id: basic_token
      enabled: true
      pattern: \b[Bb]asic\s+[A-Za-z0-9+/]{18,}={0,2}\b
    - id: auth_token
      enabled: true
      pattern: '["''''\[]*[Aa]uthorization["''''\]]*\s*[:=]\s*[''''"]?\b(?:[Tt]oken\s+)?[a-zA-Z0-9\-_+/]{20,500}[''''"]?'
    - id: private_key
      enabled: true
      pattern: '-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY\s*?-----[a-zA-Z0-9\/\n\r=+]*-----\s*?END[ A-Z0-9_-]*? PRIVATE KEY\s*?-----'
    - id: gitlab_v2_token
      enabled: true
      pattern: \b(glpat-[a-zA-Z0-9\-=_]{20,22})\b
    - id: github_token
      enabled: true
      pattern: \b((?:ghp|gho|ghu|ghs|ghr|github_pat)_[a-zA-Z0-9_]{36,255})\b
    - id: qcloud_api_gateway_appkey
      enabled: true
      pattern: \bAPID[a-zA-Z0-9]{32,42}\b
    - id: wechat_appid
      enabled: true
      pattern: '["''''](wx[a-z0-9]{15,18})["'''']'
    - id: wechat_corpid
      enabled: true
      pattern: '["''''](ww[a-z0-9]{15,18})["'''']'
    - id: wechat_id
      enabled: true
      pattern: '["''''](gh_[a-z0-9]{11,13})["'''']'
    - id: password
      enabled: true
      pattern: (?i)(?:admin_?pass|password|[a-z]{3,15}_?password|user_?pass|user_?pwd|admin_?pwd)\\?['"]*\s*[:=]\s*\\?['"][a-z0-9!@#$%&*]{5,50}\\?['"]
    - id: wechat_webhookurl
      enabled: true
      pattern: \bhttps://qyapi.weixin.qq.com/cgi-bin/webhook/send\?key=[a-zA-Z0-9\-]{25,50}\b
    - id: dingtalk_webhookurl
      enabled: true
      pattern: \bhttps://oapi.dingtalk.com/robot/send\?access_token=[a-z0-9]{50,80}\b
    - id: feishu_webhookurl
      enabled: true
      pattern: \bhttps://open.feishu.cn/open-apis/bot/v2/hook/[a-z0-9\-]{25,50}\b
    - id: slack_webhookurl
      enabled: true
      pattern: \bhttps://hooks.slack.com/services/[a-zA-Z0-9\-_]{6,12}/[a-zA-Z0-9\-_]{6,12}/[a-zA-Z0-9\-_]{15,24}\b
    - id: grafana_api_key
      enabled: true
      pattern: \beyJrIjoi[a-zA-Z0-9\-_+/]{50,100}={0,2}\b
    - id: grafana_cloud_api_token
      enabled: true
      pattern: \bglc_[A-Za-z0-9\-_+/]{32,200}={0,2}\b
    - id: grafana_service_account_token
      enabled: true
      pattern: \bglsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8}\b
    - id: app_key
      enabled: true
      pattern: \b(?:VUE|APP|REACT)_[A-Z_0-9]{1,15}_(?:KEY|PASS|PASSWORD|TOKEN|APIKEY)['"]*[:=]"(?:[A-Za-z0-9_\-]{15,50}|[a-z0-9/+]{50,100}==?)"
    - id: 腾讯文档
      enabled: true
      pattern: \bhttps://docs.qq.com/[a-z0-9\-]*/+[a-zA-Z0-9\-_]*
